services:
  app:
    build: .
    ports:
      - "50001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mssql

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql-data:/var/opt/mssql
